config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")

  #get 'pages/debug', to: 'pages#debug'

  get "components", to: "pages#components"


  # routes to find objects related to a user
  resources :users do
    resources :accounts, only: [:index, :edit, :update]
    resources :socials, only: [:index ]
    resources :criteria, only:[:index, :edit, :update, :show ]
  end

  #routes unique for the onboarding forms of a new candidate
  resources :accounts, only: [:new, :create, :edit, :update]
  resources :criteria, only: [:new, :create, :edit, :update, :show]
  resources :socials, only: [:new, :create, :edit, :update]



end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar-exore.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-exore">
  <div class="container-fluid ">
    <%= link_to "#", class: "navbar-brand d-flex" do %>
      <%= image_tag "Lg Exore Blue.png" %>
    <div class="">
      <h2 id="exore-title">Exore.net</h2>
    </div>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active ">
            <%#= link_to "Dashboard", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Carrier", criterium_path( @user_criterium), class: "nav-link " if @user_criterium %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if image_tag current_user.picture_url %>
              <%= image_tag current_user.picture_url, class: "avatar", alt: "dropdown menu"  %>
            <% else  %>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
            <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

              <%= link_to "Edit Account", edit_account_path( @user_account), class: "dropdown-item" if (@user_criterium && !@social.nil?) %>
              <%= link_to "Edit Criteria", edit_criterium_path( @user_criterium), class: "dropdown-item" if (@user_criterium && !@social.nil?) %>
              <%#= link_to "Edit Socials",edit_social_path( @user_social), class: "dropdown-item" if (@user_criterium && !@social.id.nil?) %>

              <%#= link_to "Components", components_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_new-account.html.erb
<%= simple_form_for(@account) do |f| %>
    <%= f.input :first_name, label: 'Name'%>
    <%= f.input :last_name, label: 'Last Name' %>
    <%= f.input :birthday ,
                :as => :date,
                :start_year => Date.today.year - 60,
                :end_year => Date.today.year - 12,
                :order => [:day, :month, :year], label: 'Birthday'%>
    <%= f.input :phone , label: 'Phone (E.G. 3005520741)'%>
    <%= f.input :email , label: 'Type your email'%>

    <div class="d-flex justify-content-center my-0">
      <%= f.submit 'Update', class:"btn-rainbow-link" %>
      <%#= link_to "Back", edit_user_registration_path  %>
    </div>
  <% end %>

app/views/shared/_new-criterium.html.erb
<div class="container"  role="combobox">

  <%= simple_form_for(@criterium) do |f| %>
      <%= f.input :search_status,
                  label: 'What is your status?',
                  collection: Criterium::SEARCH_STATUS
                  %>
      <%= f.input :notice_period,
                  label: 'Do you have a notice period?',
                  collection: Criterium::NOTICE_PERIOD %>

      <%= f.input :location,
                  label: 'Where would you like to work?'%>

      <%= f.input :remote_work_type,
                  label: 'Do you have a notice period?',
                  collection: Criterium::REMOTE_WORK_TYPE %>

      <%= f.input :salary_grid,
                  label: 'Do you have a notice period?',
                  collection: Criterium::SALARY_GRID %>

      <%= f.input :position_id,
                  label: 'what position are you targeting?',
                  collection: Position.all,
                  label_method: lambda { |position| position.position_name } %>

      <div class="d-flex justify-content-center my-0">
        <%= f.submit 'Update', class:"btn-rainbow-link" %>
        <%#= link_to "Back",  edit_account_path(account)  %>
      </div>
    <% end %>
  <ul data-autocomplete-target="results"></ul>

</div>

app/views/shared/_new-criterium_slide.html.erb
<%= simple_form_for(@criterium, data: { controller: "multi-step-form" }) do |f| %>

  <!-- First question: Search status -->
  <div class="form-page" data-multi-step-form-target="formPage">
    <%= f.label :search_status, 'What is your status?' %>
    <%= f.hidden_field :search_status %>
    <div class="button-group">
      <% Criterium::SEARCH_STATUS.each do |status| %>
        <%= link_to status, "#", class: "btn btn-option", data: { action: "click->multi-step-form#nextPage", "answer-value" => status, "param-name" => "search_status" } %>
      <% end %>
    </div>
  </div>

  <!-- Second question: Notice period -->
  <div class="form-page" data-multi-step-form-target="formPage">
    <%= f.label :notice_period, 'Do you have a notice period?' %>
    <%= f.hidden_field :notice_period %>
    <div class="button-group">
      <% Criterium::NOTICE_PERIOD.each do |period| %>
        <%= link_to period, "#", class: "btn btn-option", data: { action: "click->multi-step-form#nextPage", "answer-value" => period, "param-name" => "notice_period" } %>
      <% end %>
    </div>
  </div>

 <!-- Third question: Location -->
  <div class="form-page" data-multi-step-form-target="formPage">
    <%= f.input :location, label: 'Where would you like to work?' %>
  </div>
  <!-- Fourth question: Salary grid -->
  <div class="form-page" data-multi-step-form-target="formPage">
    <%= f.input :salary_grid, label: 'Do you have a notice period?', collection: Criterium::SALARY_GRID %>
  </div>
  <!-- Fifth question: Position -->
  <div class="form-page" data-multi-step-form-target="formPage">
    <%= f.input :position_id, label: 'what position are you targeting?', collection: Position.all, label_method: lambda { |position| position.position_name } %>
  </div>

  <div class="navigation">
    <%= f.submit 'Next', class: "btn-principal", id: "next-button", data: { multi_step_form_target: "nextButton", action: "click->multi-step-form#nextPage" } %>
    <%= f.button 'Previous', type: 'button', class: "btn-principal", id: "prev-button", data: { multi_step_form_target: "prevButton", action: "click->multi-step-form#prevPage" } %>
  </div>

<% end %>

app/views/shared/_new-social.html.erb
<%= simple_form_for(@social) do |f| %>

<div class="container-small">
    <%= f.input :twitter_url, label: 'Portafolio URL'%>
    <%= f.input :github_url, label: 'Github Profile URL' %>
    <%= f.input :stack_overflow_url , label: 'Stack Overflow Profile URL'%>
    <%#= f.input :dribble_url , label: 'Dribble Profile URL'%>

</div>

<div class="">

  <div class="d-flex justify-content-center">
      <div class="">
        <%= f.submit 'Next', class:"btn-rainbow-link" %>
        <%#= link_to "Back", edit_user_registration_path  %>
      </div>
  </div>

</div>


  <% end %>